version: 2.1

jobs:
  build-linux:
    docker:
      - image: outpostuniverse/netfix:1.0
    steps:
      - checkout
      - run: git submodule update --init
      - run: make --keep-going netFixServer
  build-linux-clang:
    docker:
      - image: outpostuniverse/netfix:1.0
    steps:
      - checkout
      - run: git submodule update --init
      - run: make --keep-going netFixServer CXX=clang++

workflows:
  build:
    jobs:
      - build-linux
      - build-linux-clang
